/*
MySQL Data Transfer
Source Host: localhost
Source Database: cmb
Target Host: localhost
Target Database: cmb
Date: 13/01/2015 21:08:12
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for desa
-- ----------------------------
CREATE TABLE `desa` (
  `id_desa` int(50) NOT NULL AUTO_INCREMENT,
  `id_kecamatan` int(50) NOT NULL,
  `nama_desa` varchar(100) NOT NULL,
  PRIMARY KEY (`id_desa`)
) ENGINE=MyISAM AUTO_INCREMENT=475 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for kabupaten
-- ----------------------------
CREATE TABLE `kabupaten` (
  `id_kabupaten` int(5) NOT NULL AUTO_INCREMENT,
  `nama_kabupaten` varchar(100) NOT NULL,
  `id_provinsi` int(5) NOT NULL,
  PRIMARY KEY (`id_kabupaten`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for kecamatan
-- ----------------------------
CREATE TABLE `kecamatan` (
  `id_kecamatan` int(10) NOT NULL AUTO_INCREMENT,
  `nama_kecamatan` varchar(100) NOT NULL,
  PRIMARY KEY (`id_kecamatan`)
) ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `desa` VALUES ('1', '1', 'Adikarso');
INSERT INTO `desa` VALUES ('2', '1', 'Argopeni');
INSERT INTO `desa` VALUES ('3', '1', 'Bandung');
INSERT INTO `desa` VALUES ('4', '1', 'Candimulyo');
INSERT INTO `desa` VALUES ('5', '1', 'Candiwulan');
INSERT INTO `desa` VALUES ('6', '1', 'Depokrejo');
INSERT INTO `desa` VALUES ('7', '1', 'Gemeksekti');
INSERT INTO `desa` VALUES ('8', '1', 'Gesikan');
INSERT INTO `desa` VALUES ('9', '1', 'Jatisari');
INSERT INTO `desa` VALUES ('10', '1', 'Jemur');
INSERT INTO `desa` VALUES ('11', '1', 'Kalibagor');
INSERT INTO `desa` VALUES ('12', '1', 'Kalijirek');
INSERT INTO `desa` VALUES ('13', '1', 'Kalirejo');
INSERT INTO `desa` VALUES ('14', '1', 'Karangsari');
INSERT INTO `desa` VALUES ('15', '1', 'Kawedusan');
INSERT INTO `desa` VALUES ('16', '1', 'Kembaran');
INSERT INTO `desa` VALUES ('17', '1', 'Kutosari');
INSERT INTO `desa` VALUES ('18', '1', 'Mengkowo');
INSERT INTO `desa` VALUES ('19', '1', 'Muktirejo');
INSERT INTO `desa` VALUES ('20', '1', 'Muktisari');
INSERT INTO `desa` VALUES ('21', '1', 'Roworejo');
INSERT INTO `desa` VALUES ('22', '1', 'Sumberadi');
INSERT INTO `desa` VALUES ('23', '1', 'Tanahsari');
INSERT INTO `desa` VALUES ('24', '1', 'Wonosari');
INSERT INTO `desa` VALUES ('25', '1', 'Bumirejo');
INSERT INTO `desa` VALUES ('26', '1', 'Kebumen');
INSERT INTO `desa` VALUES ('27', '1', 'Panjer');
INSERT INTO `desa` VALUES ('28', '1', 'Selang');
INSERT INTO `desa` VALUES ('29', '1', 'Tamanwinangun');
INSERT INTO `desa` VALUES ('48', '4', 'Pejagoan');
INSERT INTO `desa` VALUES ('47', '4', 'Logede');
INSERT INTO `desa` VALUES ('46', '4', 'Kewayuhan');
INSERT INTO `desa` VALUES ('45', '4', 'Kedawung');
INSERT INTO `desa` VALUES ('44', '4', 'Kebulusan');
INSERT INTO `desa` VALUES ('43', '4', 'Kebagoran');
INSERT INTO `desa` VALUES ('42', '4', 'Karangpoh');
INSERT INTO `desa` VALUES ('41', '4', 'Jemur');
INSERT INTO `desa` VALUES ('40', '4', 'Aditiro');
INSERT INTO `desa` VALUES ('49', '4', 'Pengaringan');
INSERT INTO `desa` VALUES ('50', '4', 'Peniron');
INSERT INTO `desa` VALUES ('51', '4', 'Perigi');
INSERT INTO `desa` VALUES ('52', '4', 'Watuwalang');
INSERT INTO `desa` VALUES ('53', '5', 'Bojongsari');
INSERT INTO `desa` VALUES ('54', '5', 'Jatimulyo');
INSERT INTO `desa` VALUES ('55', '5', 'Kalijaya');
INSERT INTO `desa` VALUES ('56', '5', 'Kaliputih');
INSERT INTO `desa` VALUES ('57', '5', 'Kalirancang');
INSERT INTO `desa` VALUES ('58', '5', 'Kambangsari');
INSERT INTO `desa` VALUES ('59', '5', 'Karangkembang');
INSERT INTO `desa` VALUES ('60', '5', 'Karangtanjung');
INSERT INTO `desa` VALUES ('61', '5', 'Kemangguhan');
INSERT INTO `desa` VALUES ('62', '5', 'Krakal');
INSERT INTO `desa` VALUES ('63', '5', 'Sawangan');
INSERT INTO `desa` VALUES ('64', '5', 'Seliling');
INSERT INTO `desa` VALUES ('65', '5', 'Surotrunan');
INSERT INTO `desa` VALUES ('66', '5', 'Tanuharjo');
INSERT INTO `desa` VALUES ('67', '5', 'Tlogowulung');
INSERT INTO `desa` VALUES ('68', '5', 'Wonokromo');
INSERT INTO `desa` VALUES ('69', '6', 'Bendogarap');
INSERT INTO `desa` VALUES ('70', '6', 'Bumiharjo');
INSERT INTO `desa` VALUES ('71', '6', 'Dorowati');
INSERT INTO `desa` VALUES ('72', '6', 'Gadungrejo');
INSERT INTO `desa` VALUES ('73', '6', 'Gebangsari');
INSERT INTO `desa` VALUES ('74', '6', 'Jatimalang');
INSERT INTO `desa` VALUES ('75', '6', 'Jerukagung');
INSERT INTO `desa` VALUES ('76', '6', 'Jogosimo');
INSERT INTO `desa` VALUES ('77', '6', 'Kaliwungu');
INSERT INTO `desa` VALUES ('78', '6', 'Karangglonggong');
INSERT INTO `desa` VALUES ('79', '6', 'Kebadongan');
INSERT INTO `desa` VALUES ('80', '6', 'Kedungsari');
INSERT INTO `desa` VALUES ('81', '6', 'Kedungwinangun');
INSERT INTO `desa` VALUES ('82', '6', 'Klegenrejo');
INSERT INTO `desa` VALUES ('83', '6', 'Klegenwonosari');
INSERT INTO `desa` VALUES ('84', '6', 'Klirong');
INSERT INTO `desa` VALUES ('85', '6', 'Padanlor');
INSERT INTO `desa` VALUES ('86', '6', 'Podoluhur');
INSERT INTO `desa` VALUES ('87', '6', 'Ranterejo');
INSERT INTO `desa` VALUES ('88', '6', 'Sitirejo');
INSERT INTO `desa` VALUES ('89', '6', 'Tambakagung');
INSERT INTO `desa` VALUES ('90', '6', 'Tambakprogaten');
INSERT INTO `desa` VALUES ('91', '6', 'Tanggulangin');
INSERT INTO `desa` VALUES ('92', '6', 'Wotbuwono');
INSERT INTO `desa` VALUES ('93', '7', 'Ambalkebrek');
INSERT INTO `desa` VALUES ('94', '7', 'Ambalkliwonan');
INSERT INTO `desa` VALUES ('95', '7', 'Ambalresmi');
INSERT INTO `desa` VALUES ('96', '7', 'Ambarwinangun');
INSERT INTO `desa` VALUES ('97', '7', 'Banjarsari');
INSERT INTO `desa` VALUES ('98', '7', 'Benerkulon');
INSERT INTO `desa` VALUES ('99', '7', 'Benerwetan');
INSERT INTO `desa` VALUES ('100', '7', 'Blengorkulon');
INSERT INTO `desa` VALUES ('101', '7', 'Blengorwetan');
INSERT INTO `desa` VALUES ('102', '7', 'Dukuhrejasari');
INSERT INTO `desa` VALUES ('103', '7', 'Entak');
INSERT INTO `desa` VALUES ('104', '7', 'Gondanglegi');
INSERT INTO `desa` VALUES ('105', '7', 'Kaibon');
INSERT INTO `desa` VALUES ('106', '7', 'Kaibonpetangkuran');
INSERT INTO `desa` VALUES ('107', '7', 'Kembangsawit');
INSERT INTO `desa` VALUES ('108', '7', 'Kenayajayan');
INSERT INTO `desa` VALUES ('109', '7', 'Kradenan');
INSERT INTO `desa` VALUES ('110', '7', 'Lajer');
INSERT INTO `desa` VALUES ('111', '7', 'Pagedangan');
INSERT INTO `desa` VALUES ('112', '7', 'pasarsenen');
INSERT INTO `desa` VALUES ('113', '7', 'Peneket');
INSERT INTO `desa` VALUES ('114', '7', 'Plempukankembaran');
INSERT INTO `desa` VALUES ('115', '7', 'Prasutan');
INSERT INTO `desa` VALUES ('116', '7', 'Pucangan');
INSERT INTO `desa` VALUES ('117', '7', 'Sidareja');
INSERT INTO `desa` VALUES ('118', '7', 'Sidoluhur');
INSERT INTO `desa` VALUES ('119', '7', 'Sidomukti');
INSERT INTO `desa` VALUES ('120', '7', 'Sidomulyo');
INSERT INTO `desa` VALUES ('121', '7', 'Singosari');
INSERT INTO `desa` VALUES ('122', '7', 'Sinungreja');
INSERT INTO `desa` VALUES ('123', '7', 'Sumberjati');
INSERT INTO `desa` VALUES ('124', '7', 'Surobayan');
INSERT INTO `desa` VALUES ('125', '8', 'Ampelsari');
INSERT INTO `desa` VALUES ('126', '8', 'Banjarwinangun');
INSERT INTO `desa` VALUES ('127', '8', 'Grogolbeningsari');
INSERT INTO `desa` VALUES ('128', '8', 'Grogolpenatus');
INSERT INTO `desa` VALUES ('129', '8', 'Grujugan');
INSERT INTO `desa` VALUES ('130', '8', 'Jagamertan');
INSERT INTO `desa` VALUES ('131', '8', 'Jatimulyo');
INSERT INTO `desa` VALUES ('132', '8', 'Karangduwur');
INSERT INTO `desa` VALUES ('133', '8', 'Karanggadung');
INSERT INTO `desa` VALUES ('134', '8', 'Karangrejo');
INSERT INTO `desa` VALUES ('135', '8', 'Kebonsari');
INSERT INTO `desa` VALUES ('136', '8', 'Kritig');
INSERT INTO `desa` VALUES ('137', '8', 'Kuwangunan');
INSERT INTO `desa` VALUES ('138', '8', 'Munggu');
INSERT INTO `desa` VALUES ('139', '8', 'Nampudadi');
INSERT INTO `desa` VALUES ('140', '8', 'Petanahan');
INSERT INTO `desa` VALUES ('141', '8', 'Podourip');
INSERT INTO `desa` VALUES ('142', '8', 'Sidomulyo');
INSERT INTO `desa` VALUES ('143', '8', 'Tanjungsari');
INSERT INTO `desa` VALUES ('144', '8', 'Tegalretno');
INSERT INTO `desa` VALUES ('145', '8', 'Tresnorejo');
INSERT INTO `desa` VALUES ('146', '9', 'Arjowinangun');
INSERT INTO `desa` VALUES ('147', '9', 'Banjarrejo');
INSERT INTO `desa` VALUES ('148', '9', 'Bumirejo');
INSERT INTO `desa` VALUES ('149', '9', 'Kaleng');
INSERT INTO `desa` VALUES ('150', '9', 'Kedalemankulon');
INSERT INTO `desa` VALUES ('151', '9', 'Kedalemanwetan');
INSERT INTO `desa` VALUES ('152', '9', 'Krandegan');
INSERT INTO `desa` VALUES ('153', '9', 'Madurejo');
INSERT INTO `desa` VALUES ('154', '9', 'Pasuruhan');
INSERT INTO `desa` VALUES ('155', '9', 'Puliharjo');
INSERT INTO `desa` VALUES ('156', '9', 'Purwoharjo');
INSERT INTO `desa` VALUES ('157', '9', 'Purwosari');
INSERT INTO `desa` VALUES ('158', '9', 'Sidobunder');
INSERT INTO `desa` VALUES ('159', '9', 'Sidodadi');
INSERT INTO `desa` VALUES ('160', '9', 'Sidoharjo');
INSERT INTO `desa` VALUES ('161', '9', 'Sitiadi');
INSERT INTO `desa` VALUES ('162', '9', 'Srusuhjurutengah');
INSERT INTO `desa` VALUES ('163', '9', 'Surorejan');
INSERT INTO `desa` VALUES ('164', '9', 'Tambakmulyo');
INSERT INTO `desa` VALUES ('165', '9', 'Tukinggedong');
INSERT INTO `desa` VALUES ('166', '9', 'Waluyorejo');
INSERT INTO `desa` VALUES ('167', '9', 'Wetonkulon');
INSERT INTO `desa` VALUES ('168', '9', 'Wetonwetan');
INSERT INTO `desa` VALUES ('169', '10', 'Argopeni');
INSERT INTO `desa` VALUES ('170', '10', 'Argosari');
INSERT INTO `desa` VALUES ('171', '10', 'Ayah');
INSERT INTO `desa` VALUES ('172', '10', 'Banjararjo');
INSERT INTO `desa` VALUES ('173', '10', 'Bulurejo');
INSERT INTO `desa` VALUES ('174', '10', 'Candirenggo');
INSERT INTO `desa` VALUES ('175', '10', 'Demangsari');
INSERT INTO `desa` VALUES ('176', '10', 'Jatijajar');
INSERT INTO `desa` VALUES ('177', '10', 'Jintung');
INSERT INTO `desa` VALUES ('178', '10', 'Kalibangkang');
INSERT INTO `desa` VALUES ('179', '10', 'Kalipoh');
INSERT INTO `desa` VALUES ('180', '10', 'Karangduwur');
INSERT INTO `desa` VALUES ('181', '10', 'Kedungweru');
INSERT INTO `desa` VALUES ('182', '10', 'Mangunweni');
INSERT INTO `desa` VALUES ('183', '10', 'Pasir');
INSERT INTO `desa` VALUES ('184', '10', 'Srati');
INSERT INTO `desa` VALUES ('185', '10', 'Tlogosari');
INSERT INTO `desa` VALUES ('186', '10', 'Watukelir');
INSERT INTO `desa` VALUES ('187', '11', 'Bumiagung');
INSERT INTO `desa` VALUES ('188', '11', 'Giyanti');
INSERT INTO `desa` VALUES ('189', '11', 'Jatiluhur');
INSERT INTO `desa` VALUES ('190', '11', 'Kalisari');
INSERT INTO `desa` VALUES ('191', '11', 'Kretek');
INSERT INTO `desa` VALUES ('192', '11', 'Pringtutul');
INSERT INTO `desa` VALUES ('193', '11', 'Redisari');
INSERT INTO `desa` VALUES ('194', '11', 'Rowokele');
INSERT INTO `desa` VALUES ('195', '11', 'Sukomulyo');
INSERT INTO `desa` VALUES ('196', '11', 'Wagirpandan');
INSERT INTO `desa` VALUES ('197', '11', 'Wonoharjo');
INSERT INTO `desa` VALUES ('198', '12', 'Adiwarno');
INSERT INTO `desa` VALUES ('199', '12', 'Banyumudal');
INSERT INTO `desa` VALUES ('200', '12', 'Buayan');
INSERT INTO `desa` VALUES ('201', '12', 'Geblug');
INSERT INTO `desa` VALUES ('202', '12', 'Jatiroto');
INSERT INTO `desa` VALUES ('203', '12', 'Jladri');
INSERT INTO `desa` VALUES ('204', '12', 'Jogomulyo');
INSERT INTO `desa` VALUES ('205', '12', 'Karangbolong');
INSERT INTO `desa` VALUES ('206', '12', 'Karangsari');
INSERT INTO `desa` VALUES ('207', '12', 'Mergosono');
INSERT INTO `desa` VALUES ('208', '12', 'Nogoraji');
INSERT INTO `desa` VALUES ('209', '12', 'Pakuran');
INSERT INTO `desa` VALUES ('210', '12', 'Purbowangi');
INSERT INTO `desa` VALUES ('211', '12', 'Rangkah');
INSERT INTO `desa` VALUES ('212', '12', 'Rogodadi');
INSERT INTO `desa` VALUES ('213', '12', 'Rogodono');
INSERT INTO `desa` VALUES ('214', '12', 'Semampir');
INSERT INTO `desa` VALUES ('215', '12', 'Sikayu');
INSERT INTO `desa` VALUES ('216', '12', 'Tugu');
INSERT INTO `desa` VALUES ('217', '12', 'Wonodadi');
INSERT INTO `desa` VALUES ('218', '13', 'Banjarsari');
INSERT INTO `desa` VALUES ('219', '13', 'Kalitengah');
INSERT INTO `desa` VALUES ('220', '13', 'Kedungpuji');
INSERT INTO `desa` VALUES ('221', '13', 'Kemukus');
INSERT INTO `desa` VALUES ('222', '13', 'Klopogodo');
INSERT INTO `desa` VALUES ('223', '13', 'Panjangsari');
INSERT INTO `desa` VALUES ('224', '13', 'Patemon');
INSERT INTO `desa` VALUES ('225', '13', 'Semanding');
INSERT INTO `desa` VALUES ('226', '13', 'Semondo');
INSERT INTO `desa` VALUES ('227', '13', 'Sidayu');
INSERT INTO `desa` VALUES ('228', '13', 'Wero');
INSERT INTO `desa` VALUES ('229', '13', 'Wonosigro');
INSERT INTO `desa` VALUES ('230', '13', 'Gombong');
INSERT INTO `desa` VALUES ('231', '13', 'Wonokriyo');
INSERT INTO `desa` VALUES ('232', '14', 'Bejiruyung');
INSERT INTO `desa` VALUES ('233', '14', 'Bonosari');
INSERT INTO `desa` VALUES ('234', '14', 'Donorojo');
INSERT INTO `desa` VALUES ('235', '14', 'Jatinegoro');
INSERT INTO `desa` VALUES ('236', '14', 'Kalibeji');
INSERT INTO `desa` VALUES ('237', '14', 'Kedungjati');
INSERT INTO `desa` VALUES ('238', '14', 'Kedungwringin');
INSERT INTO `desa` VALUES ('239', '14', 'Kenteng');
INSERT INTO `desa` VALUES ('240', '14', 'Pekuncen');
INSERT INTO `desa` VALUES ('241', '14', 'sampang');
INSERT INTO `desa` VALUES ('242', '14', 'Selokerto');
INSERT INTO `desa` VALUES ('243', '14', 'Semali');
INSERT INTO `desa` VALUES ('244', '14', 'Sempor');
INSERT INTO `desa` VALUES ('245', '14', 'Sidoharum');
INSERT INTO `desa` VALUES ('246', '14', 'Somagede');
INSERT INTO `desa` VALUES ('247', '14', 'Tunjungseto');
INSERT INTO `desa` VALUES ('248', '15', 'Candi');
INSERT INTO `desa` VALUES ('249', '15', 'Giripuro');
INSERT INTO `desa` VALUES ('250', '15', 'Grenggeng');
INSERT INTO `desa` VALUES ('251', '15', 'Karangkemiri');
INSERT INTO `desa` VALUES ('252', '15', 'Pohkumbang');
INSERT INTO `desa` VALUES ('253', '15', 'Sidomulyo');
INSERT INTO `desa` VALUES ('254', '15', 'Wonorejo');
INSERT INTO `desa` VALUES ('255', '15', 'Jatiluhur');
INSERT INTO `desa` VALUES ('256', '15', 'Karanganyar');
INSERT INTO `desa` VALUES ('257', '15', 'Panjatan');
INSERT INTO `desa` VALUES ('258', '15', 'Plarangan');
INSERT INTO `desa` VALUES ('259', '16', 'Condongcampur');
INSERT INTO `desa` VALUES ('260', '16', 'Donosari');
INSERT INTO `desa` VALUES ('261', '16', 'Giwangretno');
INSERT INTO `desa` VALUES ('262', '16', 'Jabres');
INSERT INTO `desa` VALUES ('263', '16', 'Karanggedang');
INSERT INTO `desa` VALUES ('264', '16', 'Karangjambu');
INSERT INTO `desa` VALUES ('265', '16', 'Karangpule');
INSERT INTO `desa` VALUES ('266', '16', 'Karangsari');
INSERT INTO `desa` VALUES ('267', '16', 'Kejawang');
INSERT INTO `desa` VALUES ('268', '16', 'Klepungsanggar');
INSERT INTO `desa` VALUES ('269', '16', 'Menganti');
INSERT INTO `desa` VALUES ('270', '16', 'Pakuran');
INSERT INTO `desa` VALUES ('271', '16', 'Pandansari');
INSERT INTO `desa` VALUES ('272', '16', 'Pengempon');
INSERT INTO `desa` VALUES ('273', '16', 'Penusupan');
INSERT INTO `desa` VALUES ('274', '16', 'Purwodesa');
INSERT INTO `desa` VALUES ('275', '16', 'Sidoagung');
INSERT INTO `desa` VALUES ('276', '16', 'Sidoharjo');
INSERT INTO `desa` VALUES ('277', '16', 'Sruweng');
INSERT INTO `desa` VALUES ('278', '16', 'Tanggeran');
INSERT INTO `desa` VALUES ('279', '16', 'Trikarso');
INSERT INTO `desa` VALUES ('280', '17', 'Adikarto');
INSERT INTO `desa` VALUES ('281', '17', 'Adiluhur');
INSERT INTO `desa` VALUES ('282', '17', 'Adimulyo');
INSERT INTO `desa` VALUES ('283', '17', 'Arjomulyo');
INSERT INTO `desa` VALUES ('284', '17', 'Arjosari');
INSERT INTO `desa` VALUES ('285', '17', 'Banyuroto');
INSERT INTO `desa` VALUES ('286', '17', 'Bonjok');
INSERT INTO `desa` VALUES ('287', '17', 'Candi');
INSERT INTO `desa` VALUES ('288', '17', 'Wulan');
INSERT INTO `desa` VALUES ('289', '17', 'Caruban');
INSERT INTO `desa` VALUES ('290', '17', 'Joho');
INSERT INTO `desa` VALUES ('291', '17', 'Kemujan');
INSERT INTO `desa` VALUES ('292', '17', 'Mangunharjo');
INSERT INTO `desa` VALUES ('293', '17', 'Meles');
INSERT INTO `desa` VALUES ('294', '17', 'Pekuwon');
INSERT INTO `desa` VALUES ('295', '17', 'Sekarteja');
INSERT INTO `desa` VALUES ('296', '17', 'Sidamukti');
INSERT INTO `desa` VALUES ('297', '17', 'Sidamulyo');
INSERT INTO `desa` VALUES ('298', '17', 'Sugihwaras');
INSERT INTO `desa` VALUES ('299', '17', 'Tambakharjo');
INSERT INTO `desa` VALUES ('300', '17', 'Tegalsari');
INSERT INTO `desa` VALUES ('301', '17', 'Temanggal');
INSERT INTO `desa` VALUES ('302', '17', 'Tepakyang');
INSERT INTO `desa` VALUES ('303', '17', 'Wajasari');
INSERT INTO `desa` VALUES ('304', '18', 'Karanggede');
INSERT INTO `desa` VALUES ('305', '18', 'Kertodeso');
INSERT INTO `desa` VALUES ('306', '18', 'Krubungan');
INSERT INTO `desa` VALUES ('307', '18', 'Lembupurwo');
INSERT INTO `desa` VALUES ('308', '18', 'Mangunranan');
INSERT INTO `desa` VALUES ('309', '18', 'Mirit');
INSERT INTO `desa` VALUES ('310', '18', 'Miritpetikusan');
INSERT INTO `desa` VALUES ('311', '18', 'Ngabeyan');
INSERT INTO `desa` VALUES ('312', '18', 'Patukgawemulyo');
INSERT INTO `desa` VALUES ('313', '18', 'Patukrejomulyo');
INSERT INTO `desa` VALUES ('314', '18', 'Pekutan');
INSERT INTO `desa` VALUES ('315', '18', 'Rowo');
INSERT INTO `desa` VALUES ('316', '18', 'Sarwogadung');
INSERT INTO `desa` VALUES ('317', '18', 'Selotumpeng');
INSERT INTO `desa` VALUES ('318', '18', 'Singoyudan');
INSERT INTO `desa` VALUES ('319', '18', 'Sitibentar');
INSERT INTO `desa` VALUES ('320', '18', 'Tlogodepok');
INSERT INTO `desa` VALUES ('321', '18', 'Tlogopragoto');
INSERT INTO `desa` VALUES ('322', '18', 'Wergonayan');
INSERT INTO `desa` VALUES ('323', '18', 'Winong');
INSERT INTO `desa` VALUES ('324', '18', 'Wirogaten');
INSERT INTO `desa` VALUES ('325', '18', 'Wiromartan');
INSERT INTO `desa` VALUES ('326', '19', 'Babadsari');
INSERT INTO `desa` VALUES ('327', '19', 'Jlegiwinangun');
INSERT INTO `desa` VALUES ('328', '19', 'Kaliputih');
INSERT INTO `desa` VALUES ('329', '19', 'Kaliputih');
INSERT INTO `desa` VALUES ('330', '19', 'Karangsari');
INSERT INTO `desa` VALUES ('331', '19', 'Korowelang');
INSERT INTO `desa` VALUES ('332', '19', 'Kutowinangun');
INSERT INTO `desa` VALUES ('333', '19', 'Kuwarisan');
INSERT INTO `desa` VALUES ('334', '19', 'Lumbu');
INSERT INTO `desa` VALUES ('335', '19', 'Lundong');
INSERT INTO `desa` VALUES ('336', '19', 'Mekarsari');
INSERT INTO `desa` VALUES ('337', '19', 'Mrinen');
INSERT INTO `desa` VALUES ('338', '19', 'Pejagatan');
INSERT INTO `desa` VALUES ('339', '19', 'Pekunden');
INSERT INTO `desa` VALUES ('340', '19', 'Pesalakan');
INSERT INTO `desa` VALUES ('341', '19', 'Tanjungmeru');
INSERT INTO `desa` VALUES ('342', '19', 'Tanjungsari');
INSERT INTO `desa` VALUES ('343', '19', 'Tanjungseto');
INSERT INTO `desa` VALUES ('344', '19', 'Triwarno');
INSERT INTO `desa` VALUES ('345', '19', 'Ungaran');
INSERT INTO `desa` VALUES ('346', '20', 'Bagung');
INSERT INTO `desa` VALUES ('347', '20', 'Kabekelan');
INSERT INTO `desa` VALUES ('348', '20', 'Kabuaran');
INSERT INTO `desa` VALUES ('349', '20', 'Kedungbulus');
INSERT INTO `desa` VALUES ('350', '20', 'Kedungwaru');
INSERT INTO `desa` VALUES ('351', '20', 'Mulyosri');
INSERT INTO `desa` VALUES ('352', '20', 'Pecarikan');
INSERT INTO `desa` VALUES ('353', '20', 'Pesuningan');
INSERT INTO `desa` VALUES ('354', '20', 'Prembun');
INSERT INTO `desa` VALUES ('355', '20', 'Sembirkadipaten');
INSERT INTO `desa` VALUES ('356', '20', 'Sidogede');
INSERT INTO `desa` VALUES ('357', '20', 'Tersobo');
INSERT INTO `desa` VALUES ('358', '20', 'Tunggalroso');
INSERT INTO `desa` VALUES ('359', '21', 'Blater');
INSERT INTO `desa` VALUES ('360', '21', 'Jatipurus');
INSERT INTO `desa` VALUES ('361', '21', 'Jembangan');
INSERT INTO `desa` VALUES ('362', '21', 'Karangtengah');
INSERT INTO `desa` VALUES ('363', '21', 'Kebapangan');
INSERT INTO `desa` VALUES ('364', '21', 'Kedungdowo');
INSERT INTO `desa` VALUES ('365', '21', 'Lerepkebumen');
INSERT INTO `desa` VALUES ('366', '21', 'Poncowarno');
INSERT INTO `desa` VALUES ('367', '21', 'Soka');
INSERT INTO `desa` VALUES ('368', '21', 'Tegalrejo');
INSERT INTO `desa` VALUES ('369', '21', 'Tirtomoyo');
INSERT INTO `desa` VALUES ('370', '22', 'Balorejo');
INSERT INTO `desa` VALUES ('371', '22', 'Bonjokkidul');
INSERT INTO `desa` VALUES ('372', '22', 'Bonjoklor');
INSERT INTO `desa` VALUES ('373', '22', 'Bonorowo');
INSERT INTO `desa` VALUES ('374', '22', 'Mrentul');
INSERT INTO `desa` VALUES ('375', '22', 'Ngasinan');
INSERT INTO `desa` VALUES ('376', '22', 'Patukrejo');
INSERT INTO `desa` VALUES ('377', '22', 'Pujodadi');
INSERT INTO `desa` VALUES ('378', '22', 'Rowosari');
INSERT INTO `desa` VALUES ('379', '22', 'Sirnoboyo');
INSERT INTO `desa` VALUES ('380', '22', 'Tlogorejo');
INSERT INTO `desa` VALUES ('381', '23', 'Ambalkumolo');
INSERT INTO `desa` VALUES ('382', '23', 'Ampih');
INSERT INTO `desa` VALUES ('383', '23', 'Arjowinangun');
INSERT INTO `desa` VALUES ('384', '23', 'Ayamputih ');
INSERT INTO `desa` VALUES ('385', '23', 'Banjurmukadan');
INSERT INTO `desa` VALUES ('386', '23', 'Banjurpasar');
INSERT INTO `desa` VALUES ('387', '23', 'Bocor');
INSERT INTO `desa` VALUES ('388', '23', 'Brecong');
INSERT INTO `desa` VALUES ('389', '23', 'Buluspesantren');
INSERT INTO `desa` VALUES ('390', '23', 'Indrosari');
INSERT INTO `desa` VALUES ('391', '23', 'Jogopaten');
INSERT INTO `desa` VALUES ('392', '23', 'Kloposawit');
INSERT INTO `desa` VALUES ('393', '23', 'Maduretno');
INSERT INTO `desa` VALUES ('394', '23', 'Ranteringin');
INSERT INTO `desa` VALUES ('395', '23', 'Sangubanyu');
INSERT INTO `desa` VALUES ('396', '23', 'Setrojenar');
INSERT INTO `desa` VALUES ('397', '23', 'Sidomoro');
INSERT INTO `desa` VALUES ('398', '23', 'Tambakrejo');
INSERT INTO `desa` VALUES ('399', '23', 'Tanjungrejo');
INSERT INTO `desa` VALUES ('400', '23', 'Tanjungsari');
INSERT INTO `desa` VALUES ('401', '23', 'Waluyo');
INSERT INTO `desa` VALUES ('402', '24', 'Binangun');
INSERT INTO `desa` VALUES ('403', '24', 'Clapar');
INSERT INTO `desa` VALUES ('404', '24', 'Ginandong');
INSERT INTO `desa` VALUES ('405', '24', 'Giritirto');
INSERT INTO `desa` VALUES ('406', '24', 'Glontor');
INSERT INTO `desa` VALUES ('407', '24', 'Gunungsari');
INSERT INTO `desa` VALUES ('408', '24', 'Kajoran');
INSERT INTO `desa` VALUES ('409', '24', 'Kalibening');
INSERT INTO `desa` VALUES ('410', '24', 'Kalirejo');
INSERT INTO `desa` VALUES ('411', '24', 'Karanggayam');
INSERT INTO `desa` VALUES ('412', '24', 'Karangmojo');
INSERT INTO `desa` VALUES ('413', '24', 'Karangrejo');
INSERT INTO `desa` VALUES ('414', '24', 'Karangtengah');
INSERT INTO `desa` VALUES ('415', '24', 'Kebakalan');
INSERT INTO `desa` VALUES ('416', '24', 'Logandu');
INSERT INTO `desa` VALUES ('417', '24', 'Pagebangan');
INSERT INTO `desa` VALUES ('418', '24', 'Penimbun');
INSERT INTO `desa` VALUES ('419', '24', 'Selogiri');
INSERT INTO `desa` VALUES ('420', '24', 'Wonotirto');
INSERT INTO `desa` VALUES ('421', '25', 'Banioro');
INSERT INTO `desa` VALUES ('422', '25', 'Kaligending');
INSERT INTO `desa` VALUES ('423', '25', 'Kalisana');
INSERT INTO `desa` VALUES ('424', '25', 'Karangsambung');
INSERT INTO `desa` VALUES ('425', '25', 'Kedungwaru');
INSERT INTO `desa` VALUES ('426', '25', 'Langse');
INSERT INTO `desa` VALUES ('427', '25', 'Pencil');
INSERT INTO `desa` VALUES ('428', '25', 'Plumbon');
INSERT INTO `desa` VALUES ('429', '25', 'Pujotirto');
INSERT INTO `desa` VALUES ('430', '25', 'Seling');
INSERT INTO `desa` VALUES ('431', '25', 'Tlepok');
INSERT INTO `desa` VALUES ('432', '25', 'Totogan');
INSERT INTO `desa` VALUES ('433', '25', 'Wadasmalang');
INSERT INTO `desa` VALUES ('434', '25', 'Widoro');
INSERT INTO `desa` VALUES ('435', '26', 'Banjareja');
INSERT INTO `desa` VALUES ('436', '26', 'Bendungan');
INSERT INTO `desa` VALUES ('437', '26', 'Gandusari');
INSERT INTO `desa` VALUES ('438', '26', 'Gumawang');
INSERT INTO `desa` VALUES ('439', '26', 'Gunungmujil');
INSERT INTO `desa` VALUES ('440', '26', 'Harjodowo');
INSERT INTO `desa` VALUES ('441', '26', 'Jatimulya');
INSERT INTO `desa` VALUES ('442', '26', 'Kalipurwo');
INSERT INTO `desa` VALUES ('443', '26', 'Kamulyan');
INSERT INTO `desa` VALUES ('444', '26', 'Kuwarasan');
INSERT INTO `desa` VALUES ('445', '26', 'Kuwaru');
INSERT INTO `desa` VALUES ('446', '26', 'Lemahduwur');
INSERT INTO `desa` VALUES ('447', '26', 'Maduresa');
INSERT INTO `desa` VALUES ('448', '26', 'Mangli');
INSERT INTO `desa` VALUES ('449', '26', 'Ori');
INSERT INTO `desa` VALUES ('450', '26', 'Pondokgebangsari');
INSERT INTO `desa` VALUES ('451', '26', 'Purwodadi');
INSERT INTO `desa` VALUES ('452', '26', 'Sawangan');
INSERT INTO `desa` VALUES ('453', '26', 'Serut');
INSERT INTO `desa` VALUES ('454', '26', 'Sidomukti');
INSERT INTO `desa` VALUES ('455', '26', 'Tambaksari');
INSERT INTO `desa` VALUES ('456', '26', 'Wonoyoso');
INSERT INTO `desa` VALUES ('457', '27', 'Balingasal');
INSERT INTO `desa` VALUES ('458', '27', 'Kaligubuk');
INSERT INTO `desa` VALUES ('459', '27', 'Kalijering');
INSERT INTO `desa` VALUES ('460', '27', 'Merden');
INSERT INTO `desa` VALUES ('461', '27', 'Padureso');
INSERT INTO `desa` VALUES ('462', '27', 'Pejengkolan');
INSERT INTO `desa` VALUES ('463', '27', 'Rahayu');
INSERT INTO `desa` VALUES ('464', '27', 'Sendangdalem');
INSERT INTO `desa` VALUES ('465', '27', 'Sidototo');
INSERT INTO `desa` VALUES ('466', '28', 'Cangkring');
INSERT INTO `desa` VALUES ('467', '28', 'Kedunggong');
INSERT INTO `desa` VALUES ('468', '28', 'Pucangan');
INSERT INTO `desa` VALUES ('469', '28', 'Sadangkulon');
INSERT INTO `desa` VALUES ('470', '28', 'Sadangwetan');
INSERT INTO `desa` VALUES ('471', '28', 'Seboro');
INSERT INTO `desa` VALUES ('472', '28', 'Wonosari');
INSERT INTO `desa` VALUES ('473', '29', 'desabaru');
INSERT INTO `desa` VALUES ('474', '1', '');
INSERT INTO `kecamatan` VALUES ('1', 'Kebumen');
INSERT INTO `kecamatan` VALUES ('5', 'Alian');
INSERT INTO `kecamatan` VALUES ('4', 'Pejagoan');
INSERT INTO `kecamatan` VALUES ('6', 'Klirong');
INSERT INTO `kecamatan` VALUES ('7', 'Ambal');
INSERT INTO `kecamatan` VALUES ('8', 'Petanahan');
INSERT INTO `kecamatan` VALUES ('9', 'Puring');
INSERT INTO `kecamatan` VALUES ('10', 'Ayah');
INSERT INTO `kecamatan` VALUES ('11', 'Rowokele');
INSERT INTO `kecamatan` VALUES ('12', 'Buayan');
INSERT INTO `kecamatan` VALUES ('13', 'Gombong');
INSERT INTO `kecamatan` VALUES ('14', 'Sempor');
INSERT INTO `kecamatan` VALUES ('15', 'Karanganyar');
INSERT INTO `kecamatan` VALUES ('16', 'Sruweng');
INSERT INTO `kecamatan` VALUES ('17', 'Adimulyo');
INSERT INTO `kecamatan` VALUES ('18', 'Mirit');
INSERT INTO `kecamatan` VALUES ('19', 'Kutowinangun');
INSERT INTO `kecamatan` VALUES ('20', 'Prembun');
INSERT INTO `kecamatan` VALUES ('21', 'Poncowarno');
INSERT INTO `kecamatan` VALUES ('22', 'Bonorowo');
INSERT INTO `kecamatan` VALUES ('23', 'Buluspesantren');
INSERT INTO `kecamatan` VALUES ('24', 'Karanggayam');
INSERT INTO `kecamatan` VALUES ('25', 'Karangsambung');
INSERT INTO `kecamatan` VALUES ('26', 'Kuwarasan');
INSERT INTO `kecamatan` VALUES ('27', 'Padureso');
INSERT INTO `kecamatan` VALUES ('28', 'Sadang');
INSERT INTO `kecamatan` VALUES ('31', 'anyar baruuuuu');
