	<?php  
			echo"<br><br>";
				switch(@$_GET['SUB']){
				//MASTER KRY
					case'EMP_M_DAFTAR':
						include"EMP_M_DAFTAR.php";
					break;
					case'EMP_M_EMP':
						include"EMP_M_EMP.php";
					break;
					case'EMP_M_DAFTAR_02':
						include"EMP_M_DAFTAR_02.php";
					break;
					case'EMP_M_DAFTAR_02_UPDATE_GL':
						include"EMP_M_DAFTAR_02_UPDATE_GL.php";
					break;
					case'EMP_M_DAFTAR_02_DWN_01':
						include"EMP_M_DAFTAR_02_DWN_01.php";
					break;
					case'EMP_M_EMP_UPDATE':
						include"EMP_M_EMP_UPDATE.php";
					break;
					case'EMP_M_AKUN_M':
						include"EMP_M_AKUN_M.php";
					break;
					case'EMP_M_DAFTAR_REQ_01':
						include"EMP_M_DAFTAR_REQ_01.php";
					break;
					case'EMP_M_PESAN_M':
						include"EMP_M_PESAN_M.php";
					break;
				//MASTER KOP
					case'APP_DUTY_01':
						include"APP_DUTY_01.php";
					break;
					case'APP_DUTY_IN_DAFTAR':
						include"APP_DUTY_IN_DAFTAR.php";
					break;
					case'KOP_M_KOP':
						include"KOP_M_KOP.php";
					break;
					case'KOP_M_DAFTAR':
						include"KOP_M_DAFTAR.php";
					break;
					case'KOP_M_DAFTAR_MENU':
						include"KOP_M_DAFTAR_MENU.php";
					break;
					case'KOP_M_DAFTAR_EKS':
						include"KOP_M_DAFTAR_EKS.php";
					break;
					case'KOP_M_DAFTAR_IN':
						include"KOP_M_DAFTAR_IN.php";
					break;
					case'KOP_M_CARI_TGL':
						include"KOP_M_CARI_TGL.php";
					break;
					case'KOP_M_CATATAN':
						include"KOP_M_CATATAN.php";
					break;
					case'RPT_M':
						include"RPT_M.php";
					break;
					
				//DIV
					case'DIV_M_DIV':
						include"DIV_M_DIV.php";
					break;
					case'DIV_M_DIV_M':
						include"DIV_M_DIV_M.php";
					break;
					case'DIV_M_DIV_POS':
						include"DIV_M_DIV_POS.php";
					break;
					case'DIV_M_KEL_BIDANG':
						include"DIV_M_KEL_BIDANG.php";
					break;
				//FINANCE
				/**/
					case'FIN_M_FIN_TYPE':
						include"FIN_M_FIN_TYPE.php";
					break;
					case'FIN_M_FIN_GAJI':
						include"FIN_M_FIN_GAJI.php";
					break;
					case'FIN_M_FIN_GAJI_SLIP':
						include"FIN_M_FIN_GAJI_SLIP.php";
					break;
					case'FIN_M_FIN_GAJI_POINT_M':
						include"FIN_M_FIN_GAJI_POINT_M.php";
					break;
					case'FIN_M_FIN_GAJI_THR_01':
						include"FIN_M_FIN_GAJI_THR_01.php";
					break;
					case'FIN_M_FIN_GAJI_REKAP_THR_M':
						include"FIN_M_FIN_GAJI_REKAP_THR_M.php";
					break;
					case'FIN_M_FIN_GAJI_KOM_M':
						include"FIN_M_FIN_GAJI_KOM_M.php";
					break;
					case'FIN_M_FIN_GAJI_KOM':
						include"FIN_M_FIN_GAJI_KOM.php";
					break;
					case'FIN_M_FIN_GAJI_KOM_UPLOAD':
						include"FIN_M_FIN_GAJI_KOM_UPLOAD.php";
					break;
					
					case'FIN_M_FIN_GAJI_YAKKUM':
						include"FIN_M_FIN_GAJI_YAKKUM.php";
					break;
					case'FIN_M_FIN_LEMBUR':
						include"FIN_M_FIN_LEMBUR.php";
					break;
					
				//REPORT
					case'RPT_M_DUTY_01_M':
						include"RPT_M_DUTY_01_M.php";
					break;
				//Aplikasi Jadwal Tugas / Rapat
					case'DATA_KOP_GET_02':
						include"DATA_KOP_GET_02.php";
					break;


				#E-Presece
					//--BEGINING MENU--//
					case'EP_MD_01':
						include"../EP/EP_MD_01.php";
					break;
					case'EP_APP_01':
						include"../EP/EP_APP_01.php";
					break;
				#E-SIP
				case'SIP_MD_01':
					include"../SIP/SIP_MD_01.php";
				break;
				case'SIP_APP_01':
					include"../SIP/SIP_APP_01.php";
				break;
			}		
					?> 