	<?php  
			echo"<br><br>";
				switch(@$sql_escape($_GET['SUB'])){
			/* S.A */
			//AKUN
				case'AKUN_DAFTAR':
				include"AKUN_DAFTAR.php";
				break;
			//ANGGOTA
				case'ANG_M_ANG':
						include"ANG_M_ANG.php";
					break;
				case'ANG_M_ANG_EDIT':
						include"ANG_M_ANG_EDIT.php";
				break;
				case'ANG_M_ANG_DAFTAR':
						include"ANG_M_ANG_DAFTAR.php";
					break;
			//BOOK
					case'BOOK_M_BOOK_JENIS':
						include"BOOK_M_BOOK_JENIS.php";
					break;
					case'BOOK_M_BOOK':
						include"BOOK_M_BOOK.php";
					break;
					case'BOOK_M_BOOK_DAFTAR':
						include"BOOK_M_BOOK_DAFTAR.php";
					break;
					case'BOOK_M_BOOK_EDIT':
						include"BOOK_M_BOOK_EDIT.php";
					break;
					case'BOOK_M_BOOK_UPDATE_DAFTAR':
						include"BOOK_M_BOOK_UPDATE_DAFTAR.php";
					break;
					case'BOOK_M_BOOK_UPDATE_STOCK':
						include"BOOK_M_BOOK_UPDATE_STOCK.php";
					break;
			//RATE
					case'RATE_M_RATE':
						include"RATE_M_RATE.php";
					break;
					case'RATE_M_RATE_DAFTAR':
						include"RATE_M_RATE_DAFTAR.php";
					break;
			//RACK
					case'RACK_M_RACK':
						include"RACK_M_RACK.php";
					break;
					case'RACK_M_RACK_DAFTAR':
						include"RACK_M_RACK_DAFTAR.php";
					break;
			//RENT
					case'TAKE_M_TAKE':
						include"TAKE_M_TAKE.php";
					break;
					case'TAKE_M_TAKE_02_PROSES':
						include"TAKE_M_TAKE_02_PROSES.php";
					break;
					case'TAKE_M_TAKE_02':
						include"TAKE_M_TAKE_02.php";
					break;
					case'TAKE_M_TAKE_LIST_HIS_DTL':
						include"TAKE_M_TAKE_LIST_HIS_DTL.php";
					break;
					case'TAKE_M_TAKE_LIST_HIS':
						include"TAKE_M_TAKE_LIST_HIS.php";
					break;
					
			}
					?> 