<?PHP 
        #COUNTING TOTAL 
        if($cpf_vcform01_sww['form_jenis_01']=="APN"){
            #COUNTING APN GLOBAL 
              $CN_APN_GL_01 = $IGD_CN_01 + $POINT_KDSU_01 + $CN_LAB_01 + $POINT_THORAX_01 + $CN_POINT_DPJP_01 + $CN_POINT_DPJP_01 + $POINT_PJ_01 +  $POINT_GIZI_01 + $CN_POINT_RESEP_01 + $POINT_MEDIS_01 + $CN_POINT_KPR_01 + $POINT_GIZI_02 +   $CN_POINT_DP_01 + $CN_POINT_DIAG_01 +  $CN_POINT_PREOP_01 + $CN_POINT_OBAT_01 + $CN_POINT_LET_01 + $CN_POINT_TRP_01 +  $CN_POINT_RL_01 + $CN_POINT_FEN_01 + $CN_POINT_INT_01 + $CN_POINT_TETP_01 +  $CN_POINT_OM_01 +  $CN_POINT_REV_01 + $CN_POINT_SKALA_01 + $CN_POINT_ASUPAN_01 + $CN_POINT_INTER_01 + $POINT_MAN_01 + $CN_POINT_NYERI_01 + $CN_POINT_NOC16_01 + $POINT_ASUPAN_02 + $CN_POINT_INDK_01 +  $POINT_PLNG_01 + $CN_POINT_RES_01 ;
                    
              echo"<b>TOTAL POINT <i>$CN_APN_GL_01</i></b>";

             }elseif($cpf_vcform01_sww['form_jenis_01']=="STT"){
              #COUNTING STT GLOBAL 
                $CN_APN_GL_01 = $IGD_CN_01 + $POINT_KDSU_01 + $CN_LAB_01 + $POINT_THORAX_01 + $CN_POINT_DPJP_01 + $CN_POINT_DPJP_01 + $POINT_PJ_01 +  $POINT_GIZI_01 + $CN_POINT_RESEP_01 + $POINT_MEDIS_01 + $CN_POINT_KPR_01 + $POINT_GIZI_02 +   $CN_POINT_DP_01 + $CN_POINT_DIAG_01 +  $CN_POINT_PREOP_01 + $CN_POINT_OBAT_01 + $CN_POINT_LET_01 + $CN_POINT_TRP_01 +  $CN_POINT_RL_01 + $CN_POINT_FEN_01 + $CN_POINT_INT_01 + $CN_POINT_TETP_01 +  $CN_POINT_OM_01 +  $CN_POINT_REV_01 + $CN_POINT_SKALA_01 + $CN_POINT_ASUPAN_01 + $CN_POINT_INTER_01 + $POINT_MAN_01 + $CN_POINT_NYERI_01 + $CN_POINT_NOC16_01 + $POINT_ASUPAN_02 + $CN_POINT_INDK_01 +  $POINT_PLNG_01 + $CN_POINT_RES_01 ;
                      
                echo"<b>TOTAL POINT <i>$CN_APN_GL_01</i></b>";
              }elseif($cpf_vcform01_sww['form_jenis_01']=="HRN"){
                #COUNTING STT GLOBAL 
                  $CN_APN_GL_01 = $IGD_CN_01 + $POINT_KDSU_01 + $CN_LAB_01 + $POINT_THORAX_01 + $CN_POINT_DPJP_01 + $CN_POINT_DPJP_01 + $POINT_PJ_01 +  $POINT_GIZI_01 + $CN_POINT_RESEP_01 + $POINT_MEDIS_01 + $CN_POINT_KPR_01 + $POINT_GIZI_02 +   $CN_POINT_DP_01 + $CN_POINT_DIAG_01 +  $CN_POINT_PREOP_01 + $CN_POINT_OBAT_01 + $CN_POINT_LET_01 + $CN_POINT_TRP_01 +  $CN_POINT_RL_01 + $CN_POINT_FEN_01 + $CN_POINT_INT_01 + $CN_POINT_TETP_01 +  $CN_POINT_OM_01 +  $CN_POINT_REV_01 + $CN_POINT_SKALA_01 + $CN_POINT_ASUPAN_01 + $CN_POINT_INTER_01 + $POINT_MAN_01 + $CN_POINT_NYERI_01 + $CN_POINT_NOC16_01 + $POINT_ASUPAN_02 + $CN_POINT_INDK_01 +  $POINT_PLNG_01 + $CN_POINT_RES_01 ;
                        
                  echo"<b>TOTAL POINT <i>$CN_APN_GL_01</i></b>";
               }
    ?>